### ISSUE TITLE
Unrelated message

### ISSUE THREAD

**Issue by mutairibassam** [AymanProjects/dart-flavorz#13]
If I am not mistaken the below message should be updated to point to `.flavor.json` instead of `pubspec.yml`.

https://github.com/AymanProjects/dart-flavorz/blob/2659d63a203a8d205b8a0d43fcc15f7931857664/lib/src/flavor_builder.dart#L114-L116

@AymanProjects Please type the message to be contributed by @ikema77

**Comment by AymanProjects** [comment]
You are right. It should be 'The environment that you wish to run doesn't exist in $pathToJsonConfigFile'

**Comment by ikema77** [comment]
@mutairibassam Issue fixed, thank you.

**Comment by AymanProjects** [comment]
@ikema77 please make a pull request to the dev branch

**Comment by ikema77** [comment]
@AymanProjects thank you for informing me about this. I have made a new pull as requested.
Please, let me know if everything is good now.

@mutairibassam I also want to thank you too.

**Comment by AymanProjects** [comment]
An escaped character ' issue.

If you generate the file using the command `dart run build_runner build`. The generated Environment class will have an error.

@ikema77 please, put the string of the exception message in double quotation to solve the issue.  

Then run the command again and make sure the issue is gone.

**Comment by ikema77** [comment]
@AymanProjects Fixed, I preferred to change the word "doesn't" to "does not" instead of using the double quotations for the whole string to make the message look more formal. Thank you!

**Comment by AymanProjects** [comment]
Fixed at 135be01a8559d8d46367b48fe0fee8639fb91b88
